Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]
src += Glob('*_gcc.S')

group = DefineGroup('CPU', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
