import os, sys, rtconfig
import pdb
#pdb.set_trace()

RTT_ROOT = os.path.normpath(os.getcwd() + "/../..")

sys.path = sys.path + [os.path.join(RTT_ROOT, "tools")]

from building import *

TARGET = "rtthread." + rtconfig.TARGET_EXT

env = Environment(tools=['mingw'],
	AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
	CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
	CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
	AR = rtconfig.AR, ARFLAGS = '-rc',
	LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS
)

env.PrependENVPath("PATH", rtconfig.EXEC_PATH)

Export("RTT_ROOT")
Export("rtconfig")

objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=True)

DoBuilding(TARGET, objs)
